### ISSUE TITLE
1001

### ISSUE THREAD

**Issue by sakis08** [mschne1der/dji-mavic-3-firmware-1001#1]
hi 
thanks for posting 

i tried to upload it to the ac but it only says this ....

"Hello from tmbinc, j005u and Bin4ry"
"Please do not leak this!"
"+-+-+-+-+-+-+-+-+-+-+-+-"
"Connect Mavic 3 powered off, then press any key and only then power it on!"
"+-+-+-+-+-+-+-+-+-+-+-+-"
Press any key to continue . . .
start to load image with usb
ready to download fie .\bin\e2-bootarea.img.pro.enc
the file .\bin\e2-bootarea.img.pro.enc size 229376

**Comment by sakis08** [comment]
I need you to guide me step by step of how to enable the fw into the aircraft

**Comment by sakis08** [comment]
?

**Comment by battar348** [comment]
وأنا واجهتني نفس المشكلة

**Comment by battar348** [comment]
Please help me. I tried a lot but it doesn't work in any way

**Comment by abdul1r1** [comment]
هل وجد أحدكم الحل؟!

**Comment by abdul1r1** [comment]
Did anyone find the solution?!
